//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RankenData.InterfacesSAPCognos.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargaAutomatica
    {
        public int Id { get; set; }
        public System.DateTime FechaProgramada { get; set; }
        public int Usuario { get; set; }
        public int TipoArchivo { get; set; }
        public Nullable<int> ArchivoCarga { get; set; }
        public Nullable<System.DateTime> FechaFinalizacion { get; set; }
    
        public virtual ArchivoCarga ArchivoCarga1 { get; set; }
        public virtual TipoArchivoCarga TipoArchivoCarga { get; set; }
    }
}
