//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RankenData.InterfacesSAPCognos.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaCognos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentaCognos()
        {
            this.CuentaSAP = new HashSet<CuentaSAP>();
            this.CuentaSAP1 = new HashSet<CuentaSAP>();
            this.CuentaSAP2 = new HashSet<CuentaSAP>();
        }
    
        public int Id { get; set; }
        public string Numero { get; set; }
        public string Descripcion { get; set; }
        public int AnexoId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Anexo Anexo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaSAP> CuentaSAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaSAP> CuentaSAP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentaSAP> CuentaSAP2 { get; set; }
    }
}
