//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RankenData.InterfacesSAPCognos.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaSAP
    {
        public int Id { get; set; }
        public string Numero { get; set; }
        public string Descripcion { get; set; }
        public int CuentaCognos { get; set; }
        public bool IsActive { get; set; }
        public int TipoCuentaSAP { get; set; }
        public Nullable<bool> EsOpen { get; set; }
        public Nullable<int> CuentaCargo { get; set; }
        public Nullable<int> CuentaAbono { get; set; }
    
        public virtual CuentaCognos CuentaCognos1 { get; set; }
        public virtual CuentaCognos CuentaCognos2 { get; set; }
        public virtual CuentaCognos CuentaCognos3 { get; set; }
        public virtual TipoCuentaSAP TipoCuentaSAP1 { get; set; }
    }
}
