//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RankenData.InterfacesSAPCognos.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnioFiscal
    {
        public int Id { get; set; }
        public short Anio { get; set; }
        public short AnioInicio { get; set; }
        public byte MesInicio { get; set; }
        public short AnioFin { get; set; }
        public byte MesFin { get; set; }
    }
}
