//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RankenData.InterfacesSAPCognos.Web.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AnioFiscal
    {
        public AnioFiscal()
        {
            this.SaldoInicial = new HashSet<SaldoInicial>();
        }
    
        public int Id { get; set; }
        public short Anio { get; set; }
        public short AnioInicio { get; set; }

        [Display(Name = "Mes inicio")]
        [Range(1, 12, ErrorMessage = "El valor para el {0} debe ser entre {1} y {2}.")]
        public byte MesInicio { get; set; }
        public short AnioFin { get; set; }

        [Display(Name = "Mes fin")]
        [Range(1, 12, ErrorMessage = "El valor para el {0} debe ser entre {1} y {2}.")]
        public byte MesFin { get; set; }
    
        public virtual ICollection<SaldoInicial> SaldoInicial { get; set; }
    }
}
