//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RankenData.InterfacesSAPCognos.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivoCargaDetalle
    {
        public long Id { get; set; }
        public int ArchivoCarga { get; set; }
        public int Escenario { get; set; }
        public byte Versión { get; set; }
        public short Anio { get; set; }
        public byte Mes { get; set; }
        public byte UnidadDeNegocio { get; set; }
        public string Cuenta { get; set; }
        public string Moneda { get; set; }
        public string GAAP { get; set; }
        public string Interfase { get; set; }
        public byte NominalAjustado { get; set; }
        public string Compania { get; set; }
        public string CopaniaRelacionada { get; set; }
        public decimal MovimientoDebitoPeriodo { get; set; }
        public decimal MovimientoCreditoPeriodo { get; set; }
        public decimal MovimientoDebitoAcumulado { get; set; }
        public decimal MovimientoCreditoAcumulado { get; set; }
        public decimal SaldoAcumuladoPeriodo { get; set; }
        public string HoraActualizacion { get; set; }
        public string UsuarioActualizacion { get; set; }
    
        public virtual ArchivoCarga ArchivoCarga1 { get; set; }
    }
}
