//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RankenData.InterfacesSAPCognos.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivoProcesado
    {
        public ArchivoProcesado()
        {
            this.ArchivoProcesadoDetalle = new HashSet<ArchivoProcesadoDetalle>();
        }
    
        public int Id { get; set; }
        public int CompaniaCognosId { get; set; }
        public byte Periodo { get; set; }
        public short Anio { get; set; }
        public bool ArchivoGenerado { get; set; }
        public System.DateTime FechaProcesoArchivo { get; set; }
        public int UsuarioId { get; set; }
    
        public virtual CompaniaCognos CompaniaCognos { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<ArchivoProcesadoDetalle> ArchivoProcesadoDetalle { get; set; }
    }
}
