//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RankenData.InterfacesSAPCognos.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivoCarga
    {
        public ArchivoCarga()
        {
            this.CargaAutomatica = new HashSet<CargaAutomatica>();
            this.ArchivoCargaDetalle = new HashSet<ArchivoCargaDetalle>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Identificador { get; set; }
        public System.DateTime Fecha { get; set; }
        public int TipoArchivoCarga { get; set; }
        public short Anio_Col3 { get; set; }
        public byte Mes_Col4 { get; set; }
        public int Usuario { get; set; }
    
        public virtual TipoArchivoCarga TipoArchivoCarga1 { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<CargaAutomatica> CargaAutomatica { get; set; }
        public virtual ICollection<ArchivoCargaDetalle> ArchivoCargaDetalle { get; set; }
    }
}
