//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RankenData.InterfacesSAPCognos.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivoProcesadoDetalle
    {
        public ArchivoProcesadoDetalle()
        {
            this.HistorialArchivoProcesadoDetalle = new HashSet<HistorialArchivoProcesadoDetalle>();
        }
    
        public int Id { get; set; }
        public int ArchivoProcesadoId { get; set; }
        public int TipoArchivoCreacionId { get; set; }
        public string Company { get; set; }
        public string Period { get; set; }
        public string Actuality { get; set; }
        public string Account { get; set; }
        public string CounterCompany { get; set; }
        public string Dim1 { get; set; }
        public string Dim2 { get; set; }
        public string Dim3 { get; set; }
        public string ITOpex { get; set; }
        public decimal Amount { get; set; }
        public string TransactionCurrency { get; set; }
        public decimal TransactionAmount { get; set; }
        public string Form { get; set; }
        public string AccountName { get; set; }
        public string Retrieve { get; set; }
        public string Variance { get; set; }
    
        public virtual ICollection<HistorialArchivoProcesadoDetalle> HistorialArchivoProcesadoDetalle { get; set; }
        public virtual ArchivoProcesado ArchivoProcesado { get; set; }
    }
}
