//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RankenData.InterfacesSAPCognos.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargaAutomatica
    {
        public int Id { get; set; }
        public System.DateTime FechaProgramada { get; set; }
        public string RutaArchivo { get; set; }
        public int UsuarioId { get; set; }
        public int TipoArchivo { get; set; }
        public string Email { get; set; }
        public bool WasLoaded { get; set; }
    
        public virtual TipoArchivoCarga TipoArchivoCarga { get; set; }
        public virtual User User { get; set; }
    }
}
