//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RankenData.InterfacesSAPCognos.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaRelacionada
    {
        public int Id { get; set; }
        public string NumeroCuentaRelacionada { get; set; }
        public int CuentaSAPId { get; set; }
        public int SociedadCognosId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual CuentaSAP CuentaSAP { get; set; }
        public virtual CompaniaCognos CompaniaCognos { get; set; }
    }
}
