//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RankenData.InterfacesSAPCognos.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaSAP
    {
        public CuentaSAP()
        {
            this.CuentaRelacionada = new HashSet<CuentaRelacionada>();
        }
    
        public int Id { get; set; }
        public string Numero { get; set; }
        public string Descripcion { get; set; }
        public int CuentaCognos { get; set; }
        public bool IsActive { get; set; }
        public int TipoCuentaSAP { get; set; }
    
        public virtual TipoCuentaSAP TipoCuentaSAP1 { get; set; }
        public virtual CuentaCognos CuentaCognos1 { get; set; }
        public virtual ICollection<CuentaRelacionada> CuentaRelacionada { get; set; }
    }
}
