//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RankenData.InterfacesSAPCognos.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaldoInicial
    {
        public int id { get; set; }
        public int CuentaSAPId { get; set; }
        public int CompaniaRFCId { get; set; }
        public int AnioFiscalId { get; set; }
        public decimal Saldo { get; set; }
        public string CuentaSAPValue { get; set; }
        public string CompaniaRFCValue { get; set; }
        public short AnioFiscalValue { get; set; }
    
        public virtual AnioFiscal AnioFiscal { get; set; }
        public virtual CompaniaRFC CompaniaRFC { get; set; }
        public virtual CuentaSAP CuentaSAP { get; set; }
    }
}
