//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RankenData.InterfacesSAPCognos.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaldoInicial
    {
        public int id { get; set; }
        public int CuentaCognosId { get; set; }
        public string CuentaCognosValue { get; set; }
        public int CompaniaCognosId { get; set; }
        public string CompaniaCognosValue { get; set; }
        public int AnioFiscalId { get; set; }
        public short AnioFiscalValue { get; set; }
        public decimal Saldo { get; set; }
        public bool EsCargaMasiva { get; set; }
    
        public virtual AnioFiscal AnioFiscal { get; set; }
        public virtual CuentaCognos CuentaCognos { get; set; }
        public virtual CompaniaCognos CompaniaCognos { get; set; }
    }
}
