//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RankenData.InterfacesSAPCognos.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ArchivoCarga = new HashSet<ArchivoCarga>();
            this.ArchivoProcesado = new HashSet<ArchivoProcesado>();
            this.GrupoUsuario = new HashSet<GrupoUsuario>();
            this.HistorialArchivoProcesadoDetalle = new HashSet<HistorialArchivoProcesadoDetalle>();
            this.CargaAutomatica = new HashSet<CargaAutomatica>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<ArchivoCarga> ArchivoCarga { get; set; }
        public virtual ICollection<ArchivoProcesado> ArchivoProcesado { get; set; }
        public virtual ICollection<GrupoUsuario> GrupoUsuario { get; set; }
        public virtual ICollection<HistorialArchivoProcesadoDetalle> HistorialArchivoProcesadoDetalle { get; set; }
        public virtual ICollection<CargaAutomatica> CargaAutomatica { get; set; }
    }
}
